# Production Docker Compose Configuration
# Use this for production deployments

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: peluprice-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://peluprice:peluprice123@db:5432/peluprice
      - MQTT_HOST=mqtt
      - MQTT_PORT=1883
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-change-this-in-production}
      - ENVIRONMENT=production
      - API_VERSION=v1
    depends_on:
      db:
        condition: service_healthy
      mqtt:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - peluprice-network

  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: peluprice-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
    restart: unless-stopped
    networks:
      - peluprice-network

  db:
    image: postgres:15
    container_name: peluprice-db
    environment:
      POSTGRES_DB: peluprice
      POSTGRES_USER: peluprice
      POSTGRES_PASSWORD: peluprice123
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Add init script to ensure database is truly ready
      - ./scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U peluprice -d peluprice -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - peluprice-network

volumes:
  postgres_data:

networks:
  peluprice-network:
    driver: bridge
